### ISSUE TITLE
SDL2?

### ISSUE THREAD

**Issue by larsbrinkhoff** [aap/pdp6#2]
Are you interested in porting to SDL2?

I made an attempt to wrap some functions in order to support both SDL1 and SDL2.  But it's not working fully; it seems some blits are made to the wrong coordinates.

https://github.com/larsbrinkhoff/pdp6/tree/sdl2

**Comment by aap** [comment]
Not that interested honestly and I'm not very happy with the SDL code and the interface to the APR yet anyway...
The real goal is to build a front panel replica and use that instead: http://aap.pdp10.org/pdp6.html
If you get it to work completely I'll gladly merge it though.

**Comment by larsbrinkhoff** [comment]
Thanks for the clarification!

**Comment by aap** [comment]
Done.
