### ISSUE TITLE
Improve audiovisual experience

### ISSUE THREAD

**Issue by larsbrinkhoff** [aap/pdp6#4]
The blinkenlights front panel simulator is great!

But I know what would make it ever greater: A full 3D model of a PDP-6.  Do you know someone who is handy with 3D modelling software?  (I don't.)

And then add another sense: sound.  Clicking when flicking switches.  Whirring DECtapes.  Teletype printing.  Punching paper tape!

**Comment by larsbrinkhoff** [comment]
Of course, there's no complete PDP-6 to make a model from.  But a close approximation could be made from photos.

Sounds can be borrowed from similar peripherals.

**Comment by aap** [comment]
I'm not that bad at 3d modelling but honestly I don't really see the point if it's just a 3d model on a computer screen. I still want to finish the front panel replica with jaseg...the project has been on hiatus for way too long already.

**Comment by larsbrinkhoff** [comment]
3D printing!
