### ISSUE TITLE
Toggling switches kills pdp6

### ISSUE THREAD

**Issue by larsbrinkhoff** [aap/pdp6#8]
This commit breaks something in pdp6: 8b0849d160fc9333fa0c7098fa74de4229f79462

How to repeat:

1. Toggle "POWER".
2. Toggle either "READ IN / START" or "MEMORY / INSTRUCTION CONTINUE".
3. SDL window closes, pdp6 killed.

**Comment by aap** [comment]
Forgot to remove a test/debug thing, will be fixed in next commit.
